#!/bin/sh

export XDG_CURRENT_DESKTOP="dwl"
export XDG_SESSION_TYPE="wayland"
export XDG_MENU_PREFIX="arch-"
export QT_QPA_PLATFORM="wayland"
export QT_QPA_PLATFORMTHEME="qt6ct"

exec dwl >/dev/null 2>&1 &
